easy_admin:
    list:
        actions: ['edit', 'search', 'show']
    design:
        menu:
            - { label: 'Home', route: 'admin_home', default: true }
            - { entity: 'Admin', class: 'App\Entity\Admin' }
            - { entity: 'Category', class: 'App\Entity\Category' }
            - { entity: 'Company', class: 'App\Entity\Company' }
            - { entity: 'MiniGame', class: 'App\Entity\MiniGame' }
            - { entity: 'Order', class: 'App\Entity\Order' }
            - { entity: 'Payment', class: 'App\Entity\Payment' }
            - { entity: 'Restaurant', class: 'App\Entity\Restaurant' }
            - { entity: 'Waiter', class: 'App\Entity\Waiter' }
    user:
        display_avatar: false
        name_property_path: 'email'
    entities:
        Admin:
            class: App\Entity\Admin
            controller: 'App\Controller\AdminController'
            form:
                fields:
                - email
                - password
                - { property: 'roles', type: 'collection' }
                - fkCompany
                - fkRestaurant
                - dCreatedAt
                - dUpdatedAt
        Category:
            class: App\Entity\Category
            controller: 'App\Controller\CategoryController'
        Company:
            class: App\Entity\Company
            controller: 'App\Controller\CompanyController'
        MiniGame:
            class: App\Entity\MiniGame
            controller: 'App\Controller\MiniGameController'
            form:
                fields:
                - id
                - vName
                - vCode
                - iBadgeGoal
                - vDescription
                - bStatus
                - dCreatedAt
                - dUpdatedAt
                - fkBadge
                - { property: 'miniGameCategory', type: 'collection' }
        Order:
            class: App\Entity\Order
            controller: 'App\Controller\OrderController'
        Payment:
            class: App\Entity\Payment
            controller: 'App\Controller\PaymentController'
        Restaurant:
            class: App\Entity\Restaurant
            controller: 'App\Controller\RestaurantController'
        Waiter:
            class: App\Entity\Waiter
            controller: 'App\Controller\WaiterController'
