easy_admin:
    list:
        actions: ['edit', 'search', 'show']
    design:
        menu:
            - Admin
            - Category
            - Company
            - MiniGame
            - { entity: 'Order', default: true }
            - Payment
            - Restaurant
            - Waiter
        templates:
            menu: 'easyadmin/menu.html.twig'
    user:
        display_avatar: false
        name_property_path: 'email'
    entities:
        Admin:
            class: App\Entity\Admin
            controller: 'App\Controller\AdminController'
            form:
                fields:
                - email
                - password
                - { property: 'roles', type: 'collection' }
                - fkCompany
                - fkRestaurant
                - dCreatedAt
                - dUpdatedAt
        Category:
            class: App\Entity\Category
            controller: 'App\Controller\CategoryController'
        Company:
            class: App\Entity\Company
            controller: 'App\Controller\CompanyController'
        MiniGame:
            class: App\Entity\MiniGame
            controller: 'App\Controller\MiniGameController'
            form:
                fields:
                - id
                - vName
                - vCode
                - iBadgeGoal
                - vDescription
                - bStatus
                - dCreatedAt
                - dUpdatedAt
                - fkBadge
                - { property: 'miniGameCategory', type: 'collection' }
        Order:
            class: App\Entity\Order
            controller: 'App\Controller\OrderController'
        Payment:
            class: App\Entity\Payment
            controller: 'App\Controller\PaymentController'
        Restaurant:
            class: App\Entity\Restaurant
            controller: 'App\Controller\RestaurantController'
        Waiter:
            class: App\Entity\Waiter
            controller: 'App\Controller\WaiterController'
