easy_admin:
    design:
        menu:
            - Admin
            - Company
            - MiniGame
            - { entity: 'Order', default: true }
            - Payment
            - Restaurant
            - Waiter
        templates:
            menu: 'easyadmin/menu.html.twig'
    user:
        display_avatar: false
        name_property_path: 'email'
    entities:
        Admin:
            class: App\Entity\Admin
            controller: 'App\Controller\AdminController'
        Company:
            class: App\Entity\Company
            controller: 'App\Controller\CompanyController'
        MiniGame:
            class: App\Entity\MiniGame
            controller: 'App\Controller\MiniGameController'
        Order:
            class: App\Entity\Order
            controller: 'App\Controller\OrderController'
        Payment:
            class: App\Entity\Payment
            controller: 'App\Controller\PaymentController'
        Restaurant:
            class: App\Entity\Restaurant
            controller: 'App\Controller\RestaurantController'
        Waiter:
            class: App\Entity\Waiter
            controller: 'App\Controller\WaiterController'
