easy_admin:
    site_name: 'Administration app for Fuddie'
    list:
        actions: ['edit', 'search', 'show']
    design:
        menu:
            - { label: 'Home', route: 'admin_home', default: true }
            - { entity: 'Admin', class: 'App\Entity\ACL\Admin' }
            - { entity: 'Category', class: 'App\Entity\Category' }
            - { entity: 'Company', class: 'App\Entity\Company' }
            - { entity: 'MiniGame', class: 'App\Entity\MiniGame' }
            - { entity: 'Order', class: 'App\Entity\Order' }
            - { entity: 'Payment', class: 'App\Entity\Payment' }
            - { entity: 'Restaurant', class: 'App\Entity\Restaurant' }
            - { entity: 'Waiter', class: 'App\Entity\Waiter' }
    user:
        display_avatar: false
        name_property_path: 'email'
    entities:
        Admin:
            class: App\Entity\ACL\Admin
            controller: 'App\Controller\AdminController'
            form:
                fields:
                - email
                - password
                - { property: 'roles', type: 'collection' }
                - { property: 'companies', type: 'collection' }
                - { property: 'restaurants', type: 'collection' }
        Badge:
            class: App\Entity\Badge
        Category:
            class: App\Entity\Category
            controller: 'App\Controller\CategoryController'
            form:
                fields:
                    - vName
                    - vDescription
                    - bStatus
                    - { property: 'restaurant', type: 'entity' }
        Company:
            class: App\Entity\Company
            controller: 'App\Controller\CompanyController'
            form:
                fields:
                    - vName
                    - vWebsite
                    - vLogo
                    - vAddress
                    - vPhone
                    - jSettings
                    - bStatus
        MiniGame:
            class: App\Entity\MiniGame
            controller: 'App\Controller\MiniGameController'
            form:
                fields:
                - vName
                - vCode
                - iBadgeGoal
                - vDescription
                - bStatus
                - { property: 'fkBadge', type: 'entity' }
                - { property: 'miniGameCategory', type: 'entity' }
        MiniGameCategory:
            class: App\Entity\MiniGameCategory
        Order:
            class: App\Entity\Order
            controller: 'App\Controller\OrderController'
            form:
                fields:
                    - vUuid
                    - dSubtotal
                    - dDiscount
                    - dFee
                    - dTotal
                    - dFeePercentage
                    - vCurrency
                    - vIp
                    - vChannel
                    - { property: 'fkOrderStatus', type: 'entity' }
                    - { property: 'fkPayment', type: 'entity' }
                    - { property: 'fkRestaurant', type: 'entity' }
                    - { property: 'fkUser', type: 'entity' }
        OrderStatus:
            class: App\Entity\OrderStatus
        Payment:
            class: App\Entity\Payment
            controller: 'App\Controller\PaymentController'
            form:
                fields:
                    - vGatewayCode
                    - vGatewayStatus
                    - dTotal
                    - vCurrency
                    - { property: 'fkPaymentMethod', type: 'entity' }
                    - { property: 'orders', type: 'entity' }
        PaymentMethod:
            class: App\Entity\PaymentMethod
        Restaurant:
            class: App\Entity\Restaurant
            controller: 'App\Controller\RestaurantController'
            form:
                fields:
                    - vName
                    - vLogo
                    - vAddress
                    - vPhone
                    - vWebsite
                    - vEmail
                    - vDescription
                    - vLongitude
                    - vLatitude
                    - jSettings
                    - bStatus
                    - { property: 'fkCompany', type: 'entity' }
                    - { property: 'category', type: 'entity' }
        Waiter:
            class: App\Entity\Waiter
            controller: 'App\Controller\WaiterController'
            form:
                fields:
                - vName
                - cCode
                - bStatus
                - { property: 'fkRestaurant', type: 'easyadmin_autocomplete', type_options: { class: 'App\Entity\Restaurant' } }
        User:
            class: App\Entity\User
